name: ci

on:
  workflow_call:
    inputs:
      internal_workflow_branch:
        type: string
        description: 'Sets the branch the reusable workflow calls reusable workflow actions with'
        default: 'main'
      codechecker_max_warnings:
        type: string
        description: 'Sets the value for --max-warnings on the moodle-plugin-ci codechecker step. Defaults to -1 which means no limit.'
        default: '-1'
      extra_php_extensions:
        type: string
      extra_plugin_runners:
        type: string
      enable_behat:
        type: boolean
        default: true
      disable_behat:
        type: boolean
      release_branches:
        description: 'Required if the branch that should process releases is in a non-standard format (e.g. main or MOODLE_XX_STABLE)'
        type: string
      moodle_branches:
        description: 'Specify the MOODLE_XX_STABLE branch you want to test against'
        type: string
      min_php:
        description: 'Specify the minimum version of PHP to test against. Will exclude workflows using older versions of PHP.'
        type: string
        default: '7.4'
      ignore_paths:
        description: 'Specify custom paths for CI to ignore. Third party libraries are ignored by default.'
        type: string
        default: ''
      concurrent_skipping:
        description: 'Skip a workflow run if the same workflow is already running. See: https://github.com/fkirc/skip-duplicate-actions?tab=readme-ov-file#concurrent_skipping'
        type: string
        default: 'same_content_newer'
    secrets:
      moodle_org_token:
        required: false

jobs:
  pull_request_job:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/pr.yml
    with:
      internal_workflow_branch: ${{ inputs.internal_workflow_branch }}
      codechecker_max_warnings: ${{ inputs.codechecker_max_warnings }}
      extra_php_extensions: ${{ inputs.extra_php_extensions }}
      extra_plugin_runners: ${{ inputs.extra_plugin_runners }}
      enable_behat: ${{ inputs.enable_behat }}
      disable_behat: ${{ inputs.disable_behat }}
      disable_behat_set: ${{ github.event.inputs.disable_behat != '' }}
      release_branches: ${{ inputs.release_branches }}
      moodle_branches: ${{ inputs.moodle_branches }}
      min_php: ${{ inputs.min_php }}
      ignore_paths: ${{ inputs.ignore_paths }}
      concurrent_skipping: ${{ inputs.concurrent_skipping }}
    secrets:
      moodle_org_token: ${{ secrets.moodle_org_token }}

  push_job:
    if: github.event_name == 'push'
    uses: ./.github/workflows/push.yml
    with:
      internal_workflow_branch: ${{ inputs.internal_workflow_branch }}
      release_branches: ${{ inputs.release_branches }}
      moodle_branches: ${{ inputs.moodle_branches }}
      min_php: ${{ inputs.min_php }}
    secrets:
      moodle_org_token: ${{ secrets.moodle_org_token }}
