name: Moodle plugin CI group for Moodle 4.0+

on:
  workflow_call:
    inputs:
      extra_php_extensions:
        type: string
      extra_plugin_runners:
        type: string
      disable_behat:
        type: boolean
      disable_phplint:
        type: boolean
      disable_phpunit:
        type: boolean
      disable_grunt:
        type: boolean

jobs:
  setup:
    name: 4.0+
    env:
      IGNORE_PATHS: tests/fixtures
    runs-on: 'ubuntu-latest'

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 5432:5432

      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        database: ['mariadb', 'pgsql']
        moodle-branch: ['main']
        node: ['14.15']
        php: ['7.3']

    steps:
      - name: Run plugin setup
        uses: ././../plugin/setup/action.yml
        with:
          extra_php_extensions: ${{ inputs.extra_php_extensions }}
          extra_plugin_runners: ${{ inputs.extra_plugin_runners }}
          disable_behat: ${{ inputs.disable_behat }}
          disable_phplint: ${{ inputs.disable_phplint }}
          disable_phpunit: ${{ inputs.disable_phpunit }}
          disable_grunt: ${{ inputs.disable_grunt }}
          highest_moodle_branch: 'main'
