#
# Whenever version.php is changed, add the latest version
# to the Moodle Plugins directory at https://moodle.org/plugins
#
# revision: 2021121500
#
name: Releasing plugin group for Moodle 4.0+ in the Plugins directory

on:
  workflow_call:
    inputs:
      plugin_name:
        required: true
        type: string
      extra_plugin_runners:
        type: string
      disable_behat:
        type: boolean
      disable_phplint:
        type: boolean
      disable_phpunit:
        type: boolean
      disable_grunt:
        type: boolean
    secrets:
      moodle_org_token:
        required: true

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        database: ['pgsql']
        moodle-branch: ['master']
        node: ['14.15']
        php: ['7.3']

    steps:
      - name: Run plugin setup
        uses: ./../plugin/setup/action.yml
        with:
          extra_plugin_runners: ${{ inputs.extra_plugin_runners }}
          disable_behat: ${{ inputs.disable_behat }}
          disable_phplint: ${{ inputs.disable_phplint }}
          disable_phpunit: ${{ inputs.disable_phpunit }}
          disable_grunt: ${{ inputs.disable_grunt }}

      - name: Run plugin release
        if: ${{ matrix.moodle-branch == 'master' }}
        uses: catalyst/catalyst-moodle-workflows/.github/plugin/release@main
        with:
          plugin_name: ${{ inputs.plugin_name }}
          moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
